name = "Hexxy 4"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8634e9b6f19b175ffd76571b117611a0805805d8ac8a3fdc9d0cf4d645d2e61a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
