name: Packwiz Export
on:
  push:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  hash:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo GOBIN=/usr/local/bin go install github.com/packwiz/packwiz@latest
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - run: cd main
      - run: bash -c "rm -rf $(cat .packwizignore | xargs)"
      - run: /usr/local/bin/packwiz refresh --build
      - run: cd ..

      - uses: actions/checkout@v4
        with:
          ref: dev
          path: dev
      - run: cd dev
      - run: bash -c "rm -rf $(cat .packwizignore | xargs)"
      - run: /usr/local/bin/packwiz refresh --build
      - run: cd ..
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: hash
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
